"""initial schema

Revision ID: 0fbebc965c0e
Revises: 
Create Date: 2026-09-21 21:54:36.275149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbebc965c0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=True),
    sa.Column('cover_ref', sa.String(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('articles_included', sa.Integer(), nullable=False),
    sa.Column('articles_excluded', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('RSS', 'GUARDIAN_API', 'WEB_ARCHIVE', 'X_BOOKMARKS', name='sourcetype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_cursor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('raw_content_ref', sa.String(), nullable=True),
    sa.Column('cleaned_content_ref', sa.String(), nullable=True),
    sa.Column('plaintext', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INCLUDED', 'EXCLUDED', name='articlestatus'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_article_source_hash')
    )
    op.create_table('issue_articles',
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('chapter_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_articles')
    op.drop_table('articles')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_table('job_runs')
    op.drop_table('issues')
    # ### end Alembic commands ###
